repos:
  - repo: https://github.com/FULL-MARKS-INC/code-checker
    rev: d85ee09999340cc3adc5780f5aabe9b901544be3
    hooks:
      - id: code-checker
        stages: [pre-commit]
        types:
          - python
        exclude: promotion_client.py|user_client.py|common_client.py|account_client.py|shop_client.py
      - id: merged-code-checker
        stages: [pre-merge-commit]
        types:
          - python
        exclude: promotion_client.py|user_client.py|common_client.py|account_client.py|shop_client.py