repos:
  - repo: https://github.com/FULL-MARKS-INC/code-checker
    rev: d60d3b4a6b06bc1a4c84aac24856de0c2a151f5c
    hooks:
      - id: code-checker
        stages: [pre-commit]
        types:
          - python
        exclude: promotion_client.py|user_client.py|common_client.py|account_client.py|shop_client.py
      - id: merged-code-checker
        stages: [pre-merge-commit]
        types:
          - python
        exclude: promotion_client.py|user_client.py|common_client.py|account_client.py|shop_client.py