repos:
  - repo: https://github.com/FULL-MARKS-INC/code-checker
    rev: 173bb6011568cb73f971f9775105bff9f053eaab
    hooks:
      - id: code-checker
        stages: [pre-commit]
        types:
          - python
        exclude: promotion_client.py|user_client.py|common_client.py|account_client.py|shop_client.py
      - id: merged-code-checker
        stages: [pre-merge-commit]
        types:
          - python
        exclude: promotion_client.py|user_client.py|common_client.py|account_client.py|shop_client.py